dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  mariadb: '10.3'

cache: pip

install:
  - pip install -U configparser msgpack-python PyMySQL paramiko
  - pip install -U coveralls coverage

before_script:
  - bash .travis/init_database.sh

env:
  - PYTHONPATH=.

script:
  - python bin/blacknet-master --help
  - python bin/blacknet-sensor --help
  - python bin/blacknet-updater --help
  - python bin/blacknet-scrubber --help
  - coverage run ./runtests.py

after_script:
  - cat tests/generated/log-maestro.log
  - cat tests/generated/log-honeypot00.log

after_success:
  - coveralls
