dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"

cache: pip

addons:
  mariadb: '10.0'

install:
  - pip install -U configparser msgpack-python PyMySQL paramiko
  - pip install -U coveralls coverage

before_script:
  - mysql -u root -e 'DROP USER blacknet@localhost; CREATE USER blacknet@localhos;'
  - mysql -u root -e 'CREATE DATABASE blacknet_tests; GRANT ALL ON blacknet_tests.* TO blacknet@localhost;'
  - mysql -u root -U blacknet_tests < "${TRAVIS_BUILD_DIR}/share/blacknet-install.sql"

script:
  - coverage run ./runtests.py

after_success:
  - coveralls
